### ISSUE TITLE
Обновление треда [Операпроблемы]

### ISSUE THREAD

**Issue by kyrnbs** [ahushh/monaba#13]
> Пишу пост, отправляю - страница треда как бы перезагружается, но остается такой же, какой она была, когда я зашел на нее. Жму F5 - в треде появляются новые ответы, в т.ч. мой пост. То есть, не работает автообновление, вообще. Кнопка "получить новые посты" никак не действует.
> 
> Windows 7 x86, Opera 12.15 (Presto)

**Comment by ahushh** [comment]
Починил.
