### ISSUE TITLE
captcha doesn't work and breaks all board

### ISSUE THREAD

**Issue by Rehdzi** [ahushh/monaba#53]
![image](https://user-images.githubusercontent.com/48959158/211911190-2e257c2b-d6b9-4d2e-bfd3-bab2315e2671.png)
when I enable captcha feature on board settings and go to check it, page displays only this text
`/opt/monaba/PlainCaptcha: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)`

using Debian 10 and Docker image

**Comment by ahushh** [comment]
Seems that captcha binary file is not included in the docker image. You have to build captcha manually and place to the specified path inside docker container. Though it’s strange that you have to do it, captcha file should be included. Don’t remember why I disabled it.

Lookup “ Build captcha executable file (if you are going to use it)” section in readme file. You’ll need only Haskell stack installed to build captcha. There’s instructions in readme how to install it on your system too.

**Comment by ahushh** [comment]
As an option, you can try to uncomment lines in monads/Dockerfile that build captcha binary. And use that docker image you built.

**Comment by ahushh** [comment]
Ah, there’s a captcha binary file in repo already. No need to build it by yourself. Just put the file to the path inside the container.

**Comment by Rehdzi** [comment]
Fixed it, thank you!
